FROM node:latest

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY yarn.lock ./
RUN yarn global add react-scripts

# add app
COPY . ./app

EXPOSE 3000

CMD ["yarn", "start"]